# Generated by Django 6.1.1 on 2026-09-11 02:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapeJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255, verbose_name='Kata Kunci / Pencarian')),
                ('location', models.CharField(blank=True, default='', max_length=150, verbose_name='Kota / Lokasi')),
                ('engine', models.CharField(choices=[('playwright', 'Playwright Headless Scraper (Tanpa API Key)'), ('places_api', 'Google Places API (New)')], default='playwright', max_length=30, verbose_name='Engine')),
                ('target_count', models.PositiveIntegerField(default=30, verbose_name='Target Jumlah')),
                ('total_scraped', models.PositiveIntegerField(default=0, verbose_name='Total Didapat')),
                ('status', models.CharField(choices=[('pending', 'Menunggu'), ('running', 'Sedang Berjalan'), ('completed', 'Selesai'), ('failed', 'Gagal')], default='pending', max_length=20, verbose_name='Status')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Pesan Error')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Waktu Mulai')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Waktu Selesai')),
            ],
            options={
                'verbose_name': 'Scrape Job',
                'verbose_name_plural': 'Scrape Jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nama Tempat')),
                ('category', models.CharField(blank=True, default='', max_length=150, verbose_name='Kategori')),
                ('address', models.TextField(blank=True, default='', verbose_name='Alamat')),
                ('phone', models.CharField(blank=True, default='', max_length=100, verbose_name='Nomor Telepon')),
                ('website', models.URLField(blank=True, default='', max_length=1000, verbose_name='Website')),
                ('rating', models.FloatField(blank=True, null=True, verbose_name='Rating')),
                ('reviews_count', models.PositiveIntegerField(default=0, verbose_name='Jumlah Ulasan')),
                ('google_maps_url', models.URLField(blank=True, default='', max_length=1500, verbose_name='Link Google Maps')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Longitude')),
                ('search_query', models.CharField(blank=True, default='', max_length=255, verbose_name='Query Asal')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ditemukan Pada')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='places', to='scraper_app.scrapejob')),
            ],
            options={
                'verbose_name': 'Tempat / Bisnis',
                'verbose_name_plural': 'Daftar Tempat',
                'ordering': ['-created_at'],
            },
        ),
    ]
