# Generated by Django 6.1.1 on 2026-09-11 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='district',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Kecamatan'),
        ),
        migrations.AddField(
            model_name='scrapejob',
            name='district',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Kecamatan'),
        ),
    ]
