# Generated by Django 6.1.1 on 2026-09-11 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0002_place_district_scrapejob_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapejob',
            name='status',
            field=models.CharField(choices=[('pending', 'Menunggu'), ('running', 'Sedang Berjalan'), ('completed', 'Selesai'), ('failed', 'Gagal'), ('cancelled', 'Dibatalkan')], default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
